### ISSUE TITLE
短信系统整合

### ISSUE THREAD

**Issue by kingofhawks** [wxzjj/les#1]
1、每天定时发代办提醒。
2、代办实时提醒。

**Comment by kingofhawks** [comment]
<add key="db_adminexam3" value="server=192.168.153.241;database=wxjsj_xzsp;uid=sa;pwd=2737011" />

**Comment by kingofhawks** [comment]
我:
<add key="db_adminexam3" value="server=192.168.153.241;database=wxjsj_xzsp;uid=sa;pwd=2737011" />
我:
allcommand.allcommand.SqlEvent_other("insert into smsMessage(sendUserName,receiveUserName,sendTime,saveTime,content,receiveMobilePhone,isSend)values('" + username.Text + "','" + dtcd2.Rows[i][0].ToString() + "','" + DateTime.Now + "','" + DateTime.Now + "','" + ss11 + "','" + dtde1.Rows[0][0].ToString() + "','False')", MyConnection);

**Comment by 39189058** [comment]
已完成
